//THIS FILE IS NOT YET FINISHED
//DO NOT REQUIRE ANYTHING FROM HERE
import { SEND_AIRMAIL, GET_AIRMAIL, DELETE_AIRMAIL } from "../../util/dataActions/dataActions";

/**
 * THIS STATEMENT PROVIDES AIRMAIL APIs
 */
export const NODEVMS_PLUGIN_API_AIRMAIL = {
    SEND_AIRMAIL,
    GET_AIRMAIL,
    DELETE_AIRMAIL
}